openapi: 3.0.0
info:
  title: Airline API
  description: API for managing airlines
  version: 1.0.0
servers:
  - url: http://localhost:8501
paths:
  /airlines:
    get:
      summary: Retrieve all airlines
      description: Retrieve a list of all airlines.
      responses:
        '200':
          description: A list of airlines
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airline'
        '500':
          description: Internal server error

  /airline:
    get:
      summary: Retrieve airlines by various fields
      description: Retrieve a list of airlines filtered by query parameters.
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Name of the airline
        - in: query
          name: iata
          schema:
            type: string
          description: IATA code of the airline
        - in: query
          name: icao
          schema:
            type: string
          description: ICAO code of the airline
        - in: query
          name: callsign
          schema:
            type: string
          description: Callsign of the airline
        - in: query
          name: country
          schema:
            type: string
          description: Country of the airline
        - in: query
          name: id
          schema:
            type: integer
          description: ID of the airline
      responses:
        '200':
          description: A list of filtered airlines
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airline'
        '500':
          description: Internal server error

    post:
      summary: Create a new airline
      description: Create a new airline with the given details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Airline'
      responses:
        '201':
          description: Airline created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirlineResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /airline/{id}:
    put:
      summary: Update an existing airline
      description: Update the details of an existing airline.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the airline to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Airline'
      responses:
        '200':
          description: Airline updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirlineResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error

    delete:
      summary: Delete an airline
      description: Delete an existing airline by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the airline to delete
      responses:
        '200':
          description: Airline deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '500':
          description: Internal server error

components:
  schemas:
    Airline:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        name:
          type: string
        iata:
          type: string
        icao:
          type: string
        callsign:
          type: string
        country:
          type: string
      required:
        - id

    AirlineResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        airline:
          $ref: '#/components/schemas/Airline'

    DeleteResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
